#! /bin/bash

#DMENU_CMD="dmenu -f -i -dim 0.5 -h 17 -p slip -fn gohup -w 2560 -y 712.5 -nb '#021b21' -nf '#e8dfd6' -sb '#f2f1b9' -sf '#032c36'"

DMENU_CMD="rofi -dmenu"
RECORD_PIDFILE="/tmp/slip_record.pid"
IMAGES="/home/toqoz/img/slip"
VIDEOS="/home/toqoz/vid/slip"
DMENU_PROMPT="slip"

# Gif scale (width in pixels).  gifs over 20MB will not be accepted by imgur.
GIF_SCALE="640"

SOUND=1
