#! /bin/sh

bspc config border_width       3
bspc config window_gap         7

bspc config split_ratio         0.61803
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config bottom_padding 24
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc monitor '^1' -d    
bspc monitor '^2' -d  

bspc rule -a termite floating=on
bspc rule -a Steam desktop=^6
bspc rule -a Pidgin desktop=^2 pseudo_tiled=on
bspc rule -a Popcorntime desktop=^3
bspc rule -a thunar floating=on
bspc rule -a Thunar floating=on
bspc rule -a transparent_blank border=false
bspc rule -a Mumble pseudo_tiled=on

bspc config focused_border_color '#6F9990'
bspc config normal_border_color '#202020'
bspc config presel_border_color '#687fd8'
bspc config urgent_border_color '#bc3451'

sxhkd &
compton --config ~/.config/compton/compton.conf -b &
xset +fp /usr/share/fonts/local &
xset fp rehash &
xsetroot -cursor_name left_ptr &
xset r rate 200 30 &
xrdb -merge ~/.Xresources &
nitrogen --restore &
panel &
nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1' &
python /home/toqoz/code/python/yarn/yarn.py &

#python /home/toqoz/code/notification/notification.py &

#LD_PRELOAD="libpthread.so.0 libGL.so.1" __GL_THREADED_OPTIMIZATIONS=1
