#! /bin/bash

. panel_colors

#if [ $(pgrep -cx panel) -gt 100 ] ; then
if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
while true; do clock -f "S%{F$COLOR_ALT_FG}%{T3}%{T1}%{B$COLOR_ALT_FG}%{F$COLOR_ICON_FG}%{T2}  %{T1}%{F$COLOR_STATUS_FG}%A %{F$COLOR_BACKGROUND}%{T3}%{T1}%{F$COLOR_STATUS_FG} %d|%m %{F$COLOR_BACKGROUND}%{T3}%{T1}%{F$COLOR_STATUS_FG} $(~/code/shell/lowercase.sh `clock -f %H`)/%M" | sed -e 's/day/'%{F$COLOR_STATUS_FG}'day'%{F$COLOR_STATUS_FG}'/' > "$PANEL_FIFO"; sleep 3; done &
while true; do pactl list sinks | sed -n '10 p' | awk -F" / " '{ print $2 }' | sed -e 's/ //' -e 's/^/A/' > "$PANEL_FIFO"; sleep 3; done &
while true; do sensors | awk -F"  +" '/+/ { print $2 }' | sed -n '4 p' | sed -e 's/C//' -e 's/\+/C/' -e 's/\.0//' > "$PANEL_FIFO"; sleep 3; done &
while true; do nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader | sed -e 's/^/G/' -e 's/$/°/' > "$PANEL_FIFO"; sleep 3; done &
#while true; do S=3; F=/sys/class/net/enp3s0/statistics/rx_bytes; X=`cat $F`; sleep $S; Y=`cat $F`; BPS="$(((Y-X)/S))"; echo | expr $BPS / 1024 | sed -e 's/^/D/' > "$PANEL_FIFO"; done &
#while true; do S=3; F=/sys/class/net/enp3s0/statistics/tx_bytes; X=`cat $F`; sleep $S; Y=`cat $F`; BPS="$(((Y-X)/S))"; echo | expr $BPS / 1024 | sed -e 's/^/U/' > "$PANEL_FIFO"; done &
#while true; do mpc | head -1 | sed -e 's/^/M/' > "$PANEL_FIFO"; sleep 3; done &


panel_bar < "$PANEL_FIFO" | lemonbar -b -g 2560x17+0+7 -f "GohuFont:size=11" -f "siji:size=11" -f "Inconsolata:size=16" -o -7 -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
    sleep 0.05
    wid=$(xdo id -a "$PANEL_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
#⌜⌟
# 
